### ISSUE TITLE
Explicar melhor no CONTRIBUINDO o tipo de conteúdo esperado

### ISSUE THREAD

**Issue by schmidt-marcelo** [ThoughtWorksInc/guia-de-desenvolvimento-tecnico#32]

**Comment by anikarni** [comment]
@schmidt-marcelo , qual era exatamente o objetivo desse issue? Eu lembro que conversamos sobre isso, mas não sei ao certo o que precisa ser deixado mais claro.

valeu!

**Comment by schmidt-marcelo** [comment]
Pois é @anikarni, eu também não lembro mais, acho que o @roberto tem mais contexto

**Comment by anikarni** [comment]
Podemos fechar esse issue, @roberto e @schmidt-marcelo ?

**Comment by schmidt-marcelo** [comment]
Por mim, sim, podemos.
