### ISSUE TITLE
Mover sessão "Saiba utilizar uma IDE e/ou editor de texto"

### ISSUE THREAD

**Issue by anikarni** [ThoughtWorksInc/guia-de-desenvolvimento-tecnico#35]
Para que o novo desenvolvedor não se apegue a uma IDE ou um editor antes de começar seu aprendizado em uma linguagem que não seja compatível (ou, pelo menos, ideal), acho legal a ideia de deixar essa sessão após a de aprendizado de uma linguagem.

A ideia seria primeiro ter "aprender uma linguagem OO" e "aprender uma linguagem funcional", e depois uma sessão de "conhecer seu editor e/ou IDE". Assim, podemos aprofundar o assunto de não só entender o valor da IDE/editor, mas também de conhecer shortcuts, dicas, etc. Acho essa uma parte essencial de desenvolvimento.

O que acham?

**Comment by roberto** [comment]
PBPM :)

Concordo! Podemos até falar de conhecer bem as ferramentas que utiliza (no caso para codificar). Isso me lembra de uma das [dicas do Pragmatic Programmer](https://pragprog.com/the-pragmatic-programmer/extracts/tips):
> **Use a Single Editor Well**
> The editor should be an extension of your hand; make sure your editor is configurable, extensible, and programmable.

**Comment by jeffhsta** [comment]
@anikarni e @roberto eu concordo com vocês, eu acho até que poderíamos falar de editor/IDE antes de falar de pareamento, porque isso pode ser um pré requisito quando se for falar de pareamento remoto, o que acham?
