### ISSUE TITLE
[Contribuidores/Curadores] Define responsabilidades de curadores vs. contribuidores

### ISSUE THREAD

**Issue by schmidt-marcelo** [ThoughtWorksInc/guia-de-desenvolvimento-tecnico#64]
Definir quais são as atribuições e expectativas para contribuidores e de curadores.

Depois de definidos esses pontos, será criado um documento para listar as responsabilidades dos contribuidores (CONTRIBUIDOR.md) e outro para as responsabilidades do curador (CURADOR.md)

**Comment by anikarni** [comment]
Bom, não sei se ficou claro que o propósito do issue é poder abrir a discussão aqui entre todos de como o guia pode se auto-organizar.

Temos em mente ter dois ou três tipos de colaboradores, mas nunca ficou muito claro aqui as expectativas de cada role. Então vou começar aqui a descrever os papéis como vejo e me digam se é isso mesmo!

### Contribuidores

Contribuidores podem vir de qualquer canto, sem nenhum pre-requisito. Muitas vezes, a contribuidora é uma ThoughtWorker que já estudou algum tópico presente no guia e conhece um pouco mais sobre o assunto, ou uma usuária que fez uso dos recursos e viu que faltam informações. A contribuidora:

* Adiciona recursos que conhece
* Atualiza links quando vê que algum link está desatualizado
* Cria pull requests
* Atualiza pull request quando tem comentários
* Pode ajudar implementando as melhoras para as quais já existem issues ou criar issues a serem priorizados

### Campeões

Campeões são o grupo de pessoas que garante que cada tópico se mantenha atualizado. Teríamos somente uma campeã (ou duas) por tópico e normalmente essa campeã tem um pouco mais de conhecimento sobre o tópico que ela se responsabiliza por. A campeã:

* Participa do grupo do slack, myTW
* Garante que o tópico de sua responsabilidade está claro, atualizado, curado, e que está sempre em andamento
* Busca contribuidores para adicionar recursos ou subtópicos a sua sessão
* Está sempre em comunicação com os curadores
* Se compromete a revisar todos os pull requests da sua sessão

### Curadores

Curadores são um grupo definido de pessoas que garante que o guia segue os padrões e se mantem atualizado, pede feedbacks, busca melhoras, e se compromete a manter a visão do guia. Curadores são ThoughtWorkers voluntárias que só tem o pre-requisito de estar alinhadas com a visão e os compromissos. Uma curadora:

* Participa do grupo do slack, myTW, e é admin do repositório
* Se compromete a revisar pull requests frequentemente (guardando pelo menos uns 20 minutos por semana para esse propósito)
* Responde a perguntas em issues, emails, comentários
* Ajuda a implementar as melhoras que foram priorizadas nos issues
* Cria novos issues com os feedbacks de usuárias
* Dissemina o guia para outras comunidades
* Busca sempre novos colaboradores e campeões
* Oferece ajuda a campeões, contribuidores e usuárias

**Comment by anikarni** [comment]
Alguma sugestão mais, @roberto , @schmidt-marcelo , @bymarkone , @jeffhsta , @ramalho , @glauco , @kchnr , @andressa , @pedrro , @danilo-barboza , @carolinaborim , @rogeriochaves , e todas as pessoas que já contribuiram para o guia até hoje? Sentiram falta de algo?

**Comment by schmidt-marcelo** [comment]
Tá ótimo, @anikarni .

Muito bom, eu não senti falta de nada. Essa semana compilo os arquivos com os teus inputs, pode ser?

**Comment by roberto** [comment]
PBPM!

**Comment by roberto** [comment]
@anikarni, obrigado por fazer esse compilado! <3

**Comment by schmidt-marcelo** [comment]
Já está no master. Valeu gurizada. :)
