### ISSUE TITLE
Colher métricas de visualizações

### ISSUE THREAD

**Issue by pedrro** [ThoughtWorksInc/guia-de-desenvolvimento-tecnico#66]
Já foi levantada alguma questão sobre, como podemos colher métricas de visualizações do projeto?
- Por exemplo, quantas pessoas já viram o guia?
- Qual sessão mais visualizada? E a menos?

Talvez isso ajudaria a definir próximos passos do projeto 😄

**Comment by andressa** [comment]
A sua sugestão seria usar Google Analytics?

O Google Analytics tem esse papel e é bem fácil utiliza-lo. É basicamente informar a url do github.io e... acompanhar o movimento =)

**Comment by anikarni** [comment]
Implementado, gente!
