### ISSUE TITLE
Projeto de Software Orientado a Objeto / OO duplicado?

### ISSUE THREAD

**Issue by rogeriochaves** [ThoughtWorksInc/guia-de-desenvolvimento-tecnico#73]
Olá!

Reparei que no guia tem duas partes de falam sobre OO, em codificação com uma breve introdução e links pra linguagens OO, e em Projeto de Software de forma bem mais detalhada, inclusive com patterns.

Na seção projeto de Software também fala de DDD (e é o tipo de coisa que esperava encontrar lá mesmo), que é uma coisa que fica entre negócio e código, enquanto padrões OO me parece algo puramente técnico, então talvez seja melhor na categoria codificação.

Ou será que não?

**Comment by anikarni** [comment]
Estou de acordo que OO é bem mais técnico e ligado a codificação, mas me pergunto o quanto a sessão de Codificação está muito mais focada em técnicas e ferramentas de codificação e menos em padrões para. Em teoria estou de acordo, mas na prática fico até com receio de ter uma sessão imensa que disincentive aprofundar conhecimento.

Seria o caso de considerar uma sessão intermediaria, onde podemos aprofundar assuntos como OO, SOLID, imutabilidade, etc?

**Comment by rogeriochaves** [comment]
Uma sessão intermediária me parece muito bom! Mas qual seria o nome? Padrões de Projeto? Ou Padrões de Código pra ficar mais claro?

**Comment by anikarni** [comment]
+1 Padrões de Código

**Comment by schmidt-marcelo** [comment]
Faz sentido, @rogeriochaves 

Seria algo como uma escadinha:
                  ______________ 
         _____| Tradução de negócio (requisitos) para código (onde entra DDD)
_____| Padrões/práticas de código
| Codificação

Domain-Driven Design na verdade permeia o segundo e o terceiro degraus. Mas faz sentido ser o último pois é necessário certo conhecimento técnico para entender DDD.
